using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace DotRocks.EntityFrameworkCore.Tests;

/// <summary>
/// Pins the SQL generated by the DotRocks date, math, and member translators. Live execution is
/// exercised by the EF Core integration suite.
/// </summary>
public sealed class DotRocksTranslatorTests
{
    [Theory]
    [InlineData("Year", "year(")]
    [InlineData("Month", "month(")]
    [InlineData("Day", "day(")]
    [InlineData("Hour", "hour(")]
    [InlineData("Minute", "minute(")]
    [InlineData("Second", "second(")]
    [InlineData("DayOfYear", "dayofyear(")]
    public void DateTimeMember_TranslatesToFunction(string member, string expectedFunction)
    {
        using var context = CreateContext();

        string sql = member switch
        {
            "Year" => context.Events.Where(e => e.OccurredAt.Year == 2026).ToQueryString(),
            "Month" => context.Events.Where(e => e.OccurredAt.Month == 6).ToQueryString(),
            "Day" => context.Events.Where(e => e.OccurredAt.Day == 25).ToQueryString(),
            "Hour" => context.Events.Where(e => e.OccurredAt.Hour == 13).ToQueryString(),
            "Minute" => context.Events.Where(e => e.OccurredAt.Minute == 14).ToQueryString(),
            "Second" => context.Events.Where(e => e.OccurredAt.Second == 15).ToQueryString(),
            _ => context.Events.Where(e => e.OccurredAt.DayOfYear == 176).ToQueryString(),
        };

        Assert.Contains(expectedFunction, sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void DateTimeAddDays_TranslatesToDaysAdd()
    {
        using var context = CreateContext();

        string sql = context
            .Events.Where(e => e.OccurredAt.AddDays(1) > e.OccurredAt)
            .ToQueryString();

        Assert.Contains("days_add(", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void DateTimeAddDays_WithWholeConstant_EmitsIntegerCount()
    {
        using var context = CreateContext();

        string sql = context
            .Events.Where(e => e.OccurredAt.AddDays(2) > e.OccurredAt)
            .ToQueryString();

        Assert.Contains("days_add(`e`.`OccurredAt`, 2)", sql, StringComparison.Ordinal);
    }

    [Fact]
    public void DateTimeAddHours_WithFractionalConstant_IsNotTranslated()
    {
        using var context = CreateContext();

        // hours_add takes a whole-number count; silently truncating 1.5 to 1 would return the
        // wrong rows, so the expression must be refused at translation time.
        InvalidOperationException exception = Assert.Throws<InvalidOperationException>(() =>
            context.Events.Where(e => e.OccurredAt.AddHours(1.5) > e.OccurredAt).ToQueryString()
        );

        Assert.Contains("translated", exception.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void DateTimeAddDays_WithParameter_GuardsAgainstFractionalCountAtExecution()
    {
        using var context = CreateContext();
        int days = 2;

        // The int variable reaches the translator as a double parameter, so the SQL carries an
        // assert_true guard that fails the query for a fractional value instead of truncating.
        string sql = context
            .Events.Where(e => e.OccurredAt.AddDays(days) > e.OccurredAt)
            .ToQueryString();

        Assert.Contains("days_add(", sql, StringComparison.Ordinal);
        Assert.Contains("assert_true(", sql, StringComparison.Ordinal);
        Assert.Contains("floor(", sql, StringComparison.Ordinal);
        Assert.Contains("whole-number count", sql, StringComparison.Ordinal);
    }

    [Fact]
    public void DateTimeConstant_InlinesAsStarRocksDateTimeLiteral()
    {
        using var context = CreateContext();

        string sql = context
            .Events.Where(e => e.OccurredAt > EF.Constant(new DateTime(2026, 1, 2, 3, 4, 5, 678)))
            .ToQueryString();

        // EF's base mapping emits TIMESTAMP '…' with seven fractional digits, which StarRocks
        // rejects; the provider must emit the DATETIME '…' literal with microsecond precision.
        Assert.Contains("DATETIME '2026-01-02 03:04:05.678000'", sql, StringComparison.Ordinal);
        Assert.DoesNotContain("TIMESTAMP", sql, StringComparison.Ordinal);
    }

    [Fact]
    public void DateTimeCollectionContains_InlinesStarRocksDateTimeLiterals()
    {
        using var context = CreateContext();
        DateTime[] dates = [new DateTime(2026, 1, 2), new DateTime(2026, 1, 3, 4, 5, 6)];

        // A constant collection expands to IN (...) with inlined literals; a captured collection
        // would bind as individual parameters and never hit the literal path.
        string sql = context
            .Events.Where(e => EF.Constant(dates).Contains(e.OccurredAt))
            .ToQueryString();

        Assert.Contains("DATETIME '2026-01-02 00:00:00.000000'", sql, StringComparison.Ordinal);
        Assert.Contains("DATETIME '2026-01-03 04:05:06.000000'", sql, StringComparison.Ordinal);
        Assert.DoesNotContain("TIMESTAMP", sql, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("Abs", "abs(")]
    [InlineData("Ceiling", "ceil(")]
    [InlineData("Floor", "floor(")]
    [InlineData("Round", "round(")]
    [InlineData("Sqrt", "sqrt(")]
    public void MathMethod_TranslatesToFunction(string method, string expectedFunction)
    {
        using var context = CreateContext();

        string sql = method switch
        {
            "Abs" => context.Events.Where(e => Math.Abs(e.Score) > 1).ToQueryString(),
            "Ceiling" => context.Events.Where(e => Math.Ceiling(e.Score) > 1).ToQueryString(),
            "Floor" => context.Events.Where(e => Math.Floor(e.Score) > 1).ToQueryString(),
            "Round" => context.Events.Where(e => Math.Round(e.Score) > 1).ToQueryString(),
            _ => context.Events.Where(e => Math.Sqrt(e.Score) > 1).ToQueryString(),
        };

        Assert.Contains(expectedFunction, sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void MathRoundWithDigits_TranslatesToRoundWithTwoArguments()
    {
        using var context = CreateContext();

        string sql = context.Events.Where(e => Math.Round(e.Score, 2) > 1).ToQueryString();

        Assert.Contains("round(", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void MathRoundWithMidpointRounding_IsNotTranslated()
    {
        using var context = CreateContext();

        // Math.Round(value, MidpointRounding) has no StarRocks equivalent. The translator must
        // decline it so EF surfaces a clear translation failure rather than emitting round(value,
        // <enum int>) that would silently round to the wrong number of digits.
        Assert.Throws<InvalidOperationException>(() =>
            context
                .Events.Where(e => Math.Round(e.Score, MidpointRounding.AwayFromZero) > 1)
                .ToQueryString()
        );
    }

    [Fact]
    public void EfFunctionsGreatest_TranslatesToGreatestFunction()
    {
        using var context = CreateContext();

        string sql = context
            .Events.Where(e => EF.Functions.Greatest(e.Score, 1.5) > 2)
            .ToQueryString();

        Assert.Contains("greatest(", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void EfFunctionsGreatest_WithThreeArguments_TranslatesToGreatestFunction()
    {
        using var context = CreateContext();

        string sql = context
            .Events.Select(e => EF.Functions.Greatest(e.Score, 1.5, 2.5))
            .ToQueryString();

        Assert.Contains("greatest(", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void EfFunctionsLeast_TranslatesToLeastFunction()
    {
        using var context = CreateContext();

        string sql = context
            .Events.Where(e =>
                EF.Functions.Least(e.OccurredAt, e.OccurredAt.AddDays(1)) > DateTime.MinValue
            )
            .ToQueryString();

        Assert.Contains("least(", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void EfStandardGreatest_WithArrayForm_TranslatesToGreatestFunction()
    {
        using var context = CreateContext();

        // An explicit array binds to the EF-standard relational params overload
        // (RelationalDbFunctionsExtensions.Greatest), which translates through the
        // GenerateGreatest visitor hook rather than the DotRocks method translator.
        string sql = context
            .Events.Select(e => EF.Functions.Greatest(new[] { e.Score, 1.5, 2.5 }))
            .ToQueryString();

        Assert.Contains("greatest(", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void EfStandardGreatest_WithFiveArguments_TranslatesToGreatestFunction()
    {
        using var context = CreateContext();

        // Five arguments exceed the DotRocks 2-4 argument overloads, so the call binds to the
        // EF-standard relational params overload.
        string sql = context
            .Events.Select(e => EF.Functions.Greatest(e.Score, 1.0, 2.0, 3.0, 4.0))
            .ToQueryString();

        Assert.Contains("greatest(", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void MathMaxAndMin_TranslateToGreatestAndLeast()
    {
        using var context = CreateContext();

        string sql = context
            .Events.Select(e => new
            {
                Larger = Math.Max(e.Score, 1.5),
                Smaller = Math.Min(e.Score, 1.5),
            })
            .ToQueryString();

        Assert.Contains("greatest(", sql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("least(", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void InlineCollectionMaxAndMin_TranslateToGreatestAndLeast()
    {
        using var context = CreateContext();

        string sql = context
            .Events.Select(e => new
            {
                Largest = new[] { e.Score, 1.5, 2.5 }.Max(),
                Smallest = new[] { e.Score, 1.5, 2.5 }.Min(),
            })
            .ToQueryString();

        Assert.Contains("greatest(", sql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("least(", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void EfFunctionsGreatest_InvokedOnClient_ThrowsInvalidOperationException()
    {
        InvalidOperationException exception = Assert.Throws<InvalidOperationException>(() =>
            EF.Functions.Greatest(1, 2)
        );

        Assert.Contains("translated", exception.Message, StringComparison.Ordinal);
    }

    private static UnitContext CreateContext()
    {
        var optionsBuilder = new DbContextOptionsBuilder<UnitContext>();
        optionsBuilder.UseStarRocks("Server=127.0.0.1;Port=9030;User ID=root");
        return new UnitContext(optionsBuilder.Options);
    }

    [SuppressMessage(
        "Performance",
        "CA1812:Avoid uninstantiated internal classes",
        Justification = "The test methods instantiate this nested context through its primary constructor."
    )]
    private sealed class UnitContext(DbContextOptions<UnitContext> options) : DbContext(options)
    {
        public DbSet<Event> Events => Set<Event>();

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Event>().ToTable("events", "unit_db").HasKey(e => e.Id);
            modelBuilder.Entity<Event>().Property(e => e.Id).ValueGeneratedNever();
        }
    }

    [SuppressMessage(
        "Performance",
        "CA1812:Avoid uninstantiated internal classes",
        Justification = "EF Core uses this entity type through DbSet metadata."
    )]
    private sealed class Event
    {
        public int Id { get; set; }

        public DateTime OccurredAt { get; set; }

        public double Score { get; set; }
    }
}
