using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace DotRocks.EntityFrameworkCore.Tests;

/// <summary>
/// Pins the SQL generated by the DotRocks date, math, and member translators. Live execution is
/// exercised by the EF Core integration suite.
/// </summary>
public sealed class DotRocksTranslatorTests
{
    [Theory]
    [InlineData("Year", "year(")]
    [InlineData("Month", "month(")]
    [InlineData("Day", "day(")]
    [InlineData("Hour", "hour(")]
    [InlineData("Minute", "minute(")]
    [InlineData("Second", "second(")]
    [InlineData("DayOfYear", "dayofyear(")]
    public void DateTimeMember_TranslatesToFunction(string member, string expectedFunction)
    {
        using var context = CreateContext();

        string sql = member switch
        {
            "Year" => context.Events.Where(e => e.OccurredAt.Year == 2026).ToQueryString(),
            "Month" => context.Events.Where(e => e.OccurredAt.Month == 6).ToQueryString(),
            "Day" => context.Events.Where(e => e.OccurredAt.Day == 25).ToQueryString(),
            "Hour" => context.Events.Where(e => e.OccurredAt.Hour == 13).ToQueryString(),
            "Minute" => context.Events.Where(e => e.OccurredAt.Minute == 14).ToQueryString(),
            "Second" => context.Events.Where(e => e.OccurredAt.Second == 15).ToQueryString(),
            _ => context.Events.Where(e => e.OccurredAt.DayOfYear == 176).ToQueryString(),
        };

        Assert.Contains(expectedFunction, sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void DateTimeAddDays_TranslatesToDaysAdd()
    {
        using var context = CreateContext();

        string sql = context
            .Events.Where(e => e.OccurredAt.AddDays(1) > e.OccurredAt)
            .ToQueryString();

        Assert.Contains("days_add(", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Theory]
    [InlineData("Abs", "abs(")]
    [InlineData("Ceiling", "ceil(")]
    [InlineData("Floor", "floor(")]
    [InlineData("Round", "round(")]
    [InlineData("Sqrt", "sqrt(")]
    public void MathMethod_TranslatesToFunction(string method, string expectedFunction)
    {
        using var context = CreateContext();

        string sql = method switch
        {
            "Abs" => context.Events.Where(e => Math.Abs(e.Score) > 1).ToQueryString(),
            "Ceiling" => context.Events.Where(e => Math.Ceiling(e.Score) > 1).ToQueryString(),
            "Floor" => context.Events.Where(e => Math.Floor(e.Score) > 1).ToQueryString(),
            "Round" => context.Events.Where(e => Math.Round(e.Score) > 1).ToQueryString(),
            _ => context.Events.Where(e => Math.Sqrt(e.Score) > 1).ToQueryString(),
        };

        Assert.Contains(expectedFunction, sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void MathRoundWithDigits_TranslatesToRoundWithTwoArguments()
    {
        using var context = CreateContext();

        string sql = context.Events.Where(e => Math.Round(e.Score, 2) > 1).ToQueryString();

        Assert.Contains("round(", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void MathRoundWithMidpointRounding_IsNotTranslated()
    {
        using var context = CreateContext();

        // Math.Round(value, MidpointRounding) has no StarRocks equivalent. The translator must
        // decline it so EF surfaces a clear translation failure rather than emitting round(value,
        // <enum int>) that would silently round to the wrong number of digits.
        Assert.Throws<InvalidOperationException>(() =>
            context
                .Events.Where(e => Math.Round(e.Score, MidpointRounding.AwayFromZero) > 1)
                .ToQueryString()
        );
    }

    private static UnitContext CreateContext()
    {
        var optionsBuilder = new DbContextOptionsBuilder<UnitContext>();
        optionsBuilder.UseStarRocks("Server=127.0.0.1;Port=9030;User ID=root");
        return new UnitContext(optionsBuilder.Options);
    }

    [SuppressMessage(
        "Performance",
        "CA1812:Avoid uninstantiated internal classes",
        Justification = "The test methods instantiate this nested context through its primary constructor."
    )]
    private sealed class UnitContext(DbContextOptions<UnitContext> options) : DbContext(options)
    {
        public DbSet<Event> Events => Set<Event>();

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Event>().ToTable("events", "unit_db").HasKey(e => e.Id);
            modelBuilder.Entity<Event>().Property(e => e.Id).ValueGeneratedNever();
        }
    }

    [SuppressMessage(
        "Performance",
        "CA1812:Avoid uninstantiated internal classes",
        Justification = "EF Core uses this entity type through DbSet metadata."
    )]
    private sealed class Event
    {
        public int Id { get; set; }

        public DateTime OccurredAt { get; set; }

        public double Score { get; set; }
    }
}
